/**
 * Generate statusline/emoji-widths.data from Unicode's Emoji_Presentation
 * property. The bash statusline renderer loads this file because awk has no
 * Unicode property escapes; server/art.ts uses the same regex directly.
 *
 * Regenerate:  bun run gen:emoji-widths
 *
 * The emitted list holds decimal codepoints in U+2600-U+27BF that default to
 * emoji rendering (2 cols). Everything outside that range is handled by
 * simple range checks in the bash/TS code, so we only need to export the
 * ambiguous Miscellaneous Symbols + Dingbats block.
 */

import { writeFileSync } from "fs";
import { join } from "path";

const OUT = join(import.meta.dir, "..", "statusline", "emoji-widths.data");

const EMOJI_PRES_RE = /\p{Emoji_Presentation}/u;
const codepoints: number[] = [];
for (let cp = 0x2600; cp <= 0x27BF; cp++) {
  if (EMOJI_PRES_RE.test(String.fromCodePoint(cp))) codepoints.push(cp);
}

const content = [
  "# Auto-generated by scripts/gen-emoji-widths.ts — do not edit by hand.",
  "# Decimal codepoints in U+2600-U+27BF with Unicode Emoji_Presentation=Yes.",
  "# Regenerate with: bun run gen:emoji-widths",
  codepoints.join(" "),
  "",
].join("\n");

writeFileSync(OUT, content);
console.log(`Wrote ${codepoints.length} codepoints to ${OUT}`);
